<?php
/**
 * AdviserFirmInvestmentManagementFirmLinkCreateSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AdviserFirmInvestmentManagementFirmLinkCreateSchema Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdviserFirmInvestmentManagementFirmLinkCreateSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdviserFirmInvestmentManagementFirmLinkCreateSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'client_relationship' => '\OpenAPI\Client\Model\ClientRelationship',
        'investment_management_firm_ref' => 'string',
        'show_all_invstrategies' => 'bool',
        'show_all_custom_index' => 'bool',
        'is_default' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'client_relationship' => null,
        'investment_management_firm_ref' => null,
        'show_all_invstrategies' => null,
        'show_all_custom_index' => null,
        'is_default' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'client_relationship' => false,
        'investment_management_firm_ref' => false,
        'show_all_invstrategies' => false,
        'show_all_custom_index' => false,
        'is_default' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'client_relationship' => 'client_relationship',
        'investment_management_firm_ref' => 'investment_management_firm_ref',
        'show_all_invstrategies' => 'show_all_invstrategies',
        'show_all_custom_index' => 'show_all_custom_index',
        'is_default' => 'is_default'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'client_relationship' => 'setClientRelationship',
        'investment_management_firm_ref' => 'setInvestmentManagementFirmRef',
        'show_all_invstrategies' => 'setShowAllInvstrategies',
        'show_all_custom_index' => 'setShowAllCustomIndex',
        'is_default' => 'setIsDefault'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'client_relationship' => 'getClientRelationship',
        'investment_management_firm_ref' => 'getInvestmentManagementFirmRef',
        'show_all_invstrategies' => 'getShowAllInvstrategies',
        'show_all_custom_index' => 'getShowAllCustomIndex',
        'is_default' => 'getIsDefault'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('client_relationship', $data ?? [], null);
        $this->setIfExists('investment_management_firm_ref', $data ?? [], null);
        $this->setIfExists('show_all_invstrategies', $data ?? [], null);
        $this->setIfExists('show_all_custom_index', $data ?? [], null);
        $this->setIfExists('is_default', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['investment_management_firm_ref'] === null) {
            $invalidProperties[] = "'investment_management_firm_ref' can't be null";
        }
        if ($this->container['show_all_invstrategies'] === null) {
            $invalidProperties[] = "'show_all_invstrategies' can't be null";
        }
        if ($this->container['show_all_custom_index'] === null) {
            $invalidProperties[] = "'show_all_custom_index' can't be null";
        }
        if ($this->container['is_default'] === null) {
            $invalidProperties[] = "'is_default' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets client_relationship
     *
     * @return \OpenAPI\Client\Model\ClientRelationship|null
     */
    public function getClientRelationship()
    {
        return $this->container['client_relationship'];
    }

    /**
     * Sets client_relationship
     *
     * @param \OpenAPI\Client\Model\ClientRelationship|null $client_relationship client_relationship
     *
     * @return self
     */
    public function setClientRelationship($client_relationship)
    {
        if (is_null($client_relationship)) {
            throw new \InvalidArgumentException('non-nullable client_relationship cannot be null');
        }
        $this->container['client_relationship'] = $client_relationship;

        return $this;
    }

    /**
     * Gets investment_management_firm_ref
     *
     * @return string
     */
    public function getInvestmentManagementFirmRef()
    {
        return $this->container['investment_management_firm_ref'];
    }

    /**
     * Sets investment_management_firm_ref
     *
     * @param string $investment_management_firm_ref investment_management_firm_ref
     *
     * @return self
     */
    public function setInvestmentManagementFirmRef($investment_management_firm_ref)
    {
        if (is_null($investment_management_firm_ref)) {
            throw new \InvalidArgumentException('non-nullable investment_management_firm_ref cannot be null');
        }
        $this->container['investment_management_firm_ref'] = $investment_management_firm_ref;

        return $this;
    }

    /**
     * Gets show_all_invstrategies
     *
     * @return bool
     */
    public function getShowAllInvstrategies()
    {
        return $this->container['show_all_invstrategies'];
    }

    /**
     * Sets show_all_invstrategies
     *
     * @param bool $show_all_invstrategies show_all_invstrategies
     *
     * @return self
     */
    public function setShowAllInvstrategies($show_all_invstrategies)
    {
        if (is_null($show_all_invstrategies)) {
            throw new \InvalidArgumentException('non-nullable show_all_invstrategies cannot be null');
        }
        $this->container['show_all_invstrategies'] = $show_all_invstrategies;

        return $this;
    }

    /**
     * Gets show_all_custom_index
     *
     * @return bool
     */
    public function getShowAllCustomIndex()
    {
        return $this->container['show_all_custom_index'];
    }

    /**
     * Sets show_all_custom_index
     *
     * @param bool $show_all_custom_index show_all_custom_index
     *
     * @return self
     */
    public function setShowAllCustomIndex($show_all_custom_index)
    {
        if (is_null($show_all_custom_index)) {
            throw new \InvalidArgumentException('non-nullable show_all_custom_index cannot be null');
        }
        $this->container['show_all_custom_index'] = $show_all_custom_index;

        return $this;
    }

    /**
     * Gets is_default
     *
     * @return bool
     */
    public function getIsDefault()
    {
        return $this->container['is_default'];
    }

    /**
     * Sets is_default
     *
     * @param bool $is_default is_default
     *
     * @return self
     */
    public function setIsDefault($is_default)
    {
        if (is_null($is_default)) {
            throw new \InvalidArgumentException('non-nullable is_default cannot be null');
        }
        $this->container['is_default'] = $is_default;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


