<?php
/**
 * ClientType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ClientType Class Doc Comment
 *
 * @category Class
 * @description [{\&quot;name\&quot;: \&quot;Individual\&quot;, \&quot;value\&quot;: \&quot;INDV\&quot;}, {\&quot;name\&quot;: \&quot;Individual Junior\&quot;, \&quot;value\&quot;: \&quot;INDV_JUNIOR\&quot;}, {\&quot;name\&quot;: \&quot;Corporate\&quot;, \&quot;value\&quot;: \&quot;CORPORATE\&quot;}, {\&quot;name\&quot;: \&quot;Trust\&quot;, \&quot;value\&quot;: \&quot;TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Charity\&quot;, \&quot;value\&quot;: \&quot;CHARITY\&quot;}, {\&quot;name\&quot;: \&quot;Partnership\&quot;, \&quot;value\&quot;: \&quot;PARTNERSHIP\&quot;}, {\&quot;name\&quot;: \&quot;Bare Trust\&quot;, \&quot;value\&quot;: \&quot;BARE_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Discretionary Trust\&quot;, \&quot;value\&quot;: \&quot;DISCRETIONARY_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Gift Trust\&quot;, \&quot;value\&quot;: \&quot;GIFT_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Ssas\&quot;, \&quot;value\&quot;: \&quot;SSAS\&quot;}]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientType
{
    /**
     * Possible values of this enum
     */
    public const INDV = 'INDV';

    public const INDV_JUNIOR = 'INDV_JUNIOR';

    public const CORPORATE = 'CORPORATE';

    public const TRUST = 'TRUST';

    public const CHARITY = 'CHARITY';

    public const PARTNERSHIP = 'PARTNERSHIP';

    public const BARE_TRUST = 'BARE_TRUST';

    public const DISCRETIONARY_TRUST = 'DISCRETIONARY_TRUST';

    public const GIFT_TRUST = 'GIFT_TRUST';

    public const SSAS = 'SSAS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INDV,
            self::INDV_JUNIOR,
            self::CORPORATE,
            self::TRUST,
            self::CHARITY,
            self::PARTNERSHIP,
            self::BARE_TRUST,
            self::DISCRETIONARY_TRUST,
            self::GIFT_TRUST,
            self::SSAS
        ];
    }
}


