<?php
/**
 * FapiDbPensionPensionClientApprovalStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FapiDbPensionPensionClientApprovalStatus Class Doc Comment
 *
 * @category Class
 * @description [{\&quot;name\&quot;: \&quot;Pending\&quot;, \&quot;value\&quot;: \&quot;PEND\&quot;}, {\&quot;name\&quot;: \&quot;Signed\&quot;, \&quot;value\&quot;: \&quot;SIGNED\&quot;}, {\&quot;name\&quot;: \&quot;Sent\&quot;, \&quot;value\&quot;: \&quot;SENT\&quot;}, {\&quot;name\&quot;: \&quot;Cancelled\&quot;, \&quot;value\&quot;: \&quot;CANC\&quot;}, {\&quot;name\&quot;: \&quot;Error\&quot;, \&quot;value\&quot;: \&quot;ERRR\&quot;}]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FapiDbPensionPensionClientApprovalStatus
{
    /**
     * Possible values of this enum
     */
    public const PEND = 'PEND';

    public const SIGNED = 'SIGNED';

    public const SENT = 'SENT';

    public const CANC = 'CANC';

    public const ERRR = 'ERRR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PEND,
            self::SIGNED,
            self::SENT,
            self::CANC,
            self::ERRR
        ];
    }
}


