<?php
/**
 * FeeScheduleReturnSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FeeScheduleReturnSchema Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FeeScheduleReturnSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FeeScheduleReturnSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'label' => 'string',
        'fee_type' => '\OpenAPI\Client\Model\FapiDbFeeFeeScheduleFeeType',
        'fee_calculation_type' => '\OpenAPI\Client\Model\FeeCalculationType',
        'fee_charge_frequency' => '\OpenAPI\Client\Model\FeeChargeFrequencyType',
        'include_initial_on_recurring_deposits' => 'bool',
        'is_vat_applicable' => 'bool',
        'ref' => 'int',
        'tiers' => '\OpenAPI\Client\Model\FeeScheduleTierReturnSchema[]',
        'date_created' => '\DateTime',
        'date_updated' => '\DateTime',
        'constraints' => '\OpenAPI\Client\Model\FeeScheduleConstraintReturnSchema'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'label' => null,
        'fee_type' => null,
        'fee_calculation_type' => null,
        'fee_charge_frequency' => null,
        'include_initial_on_recurring_deposits' => null,
        'is_vat_applicable' => null,
        'ref' => null,
        'tiers' => null,
        'date_created' => 'date-time',
        'date_updated' => 'date-time',
        'constraints' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'label' => false,
        'fee_type' => false,
        'fee_calculation_type' => false,
        'fee_charge_frequency' => false,
        'include_initial_on_recurring_deposits' => false,
        'is_vat_applicable' => false,
        'ref' => false,
        'tiers' => false,
        'date_created' => false,
        'date_updated' => false,
        'constraints' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'label' => 'label',
        'fee_type' => 'fee_type',
        'fee_calculation_type' => 'fee_calculation_type',
        'fee_charge_frequency' => 'fee_charge_frequency',
        'include_initial_on_recurring_deposits' => 'include_initial_on_recurring_deposits',
        'is_vat_applicable' => 'is_vat_applicable',
        'ref' => 'ref',
        'tiers' => 'tiers',
        'date_created' => 'date_created',
        'date_updated' => 'date_updated',
        'constraints' => 'constraints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'label' => 'setLabel',
        'fee_type' => 'setFeeType',
        'fee_calculation_type' => 'setFeeCalculationType',
        'fee_charge_frequency' => 'setFeeChargeFrequency',
        'include_initial_on_recurring_deposits' => 'setIncludeInitialOnRecurringDeposits',
        'is_vat_applicable' => 'setIsVatApplicable',
        'ref' => 'setRef',
        'tiers' => 'setTiers',
        'date_created' => 'setDateCreated',
        'date_updated' => 'setDateUpdated',
        'constraints' => 'setConstraints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'label' => 'getLabel',
        'fee_type' => 'getFeeType',
        'fee_calculation_type' => 'getFeeCalculationType',
        'fee_charge_frequency' => 'getFeeChargeFrequency',
        'include_initial_on_recurring_deposits' => 'getIncludeInitialOnRecurringDeposits',
        'is_vat_applicable' => 'getIsVatApplicable',
        'ref' => 'getRef',
        'tiers' => 'getTiers',
        'date_created' => 'getDateCreated',
        'date_updated' => 'getDateUpdated',
        'constraints' => 'getConstraints'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('fee_type', $data ?? [], null);
        $this->setIfExists('fee_calculation_type', $data ?? [], null);
        $this->setIfExists('fee_charge_frequency', $data ?? [], null);
        $this->setIfExists('include_initial_on_recurring_deposits', $data ?? [], null);
        $this->setIfExists('is_vat_applicable', $data ?? [], null);
        $this->setIfExists('ref', $data ?? [], null);
        $this->setIfExists('tiers', $data ?? [], null);
        $this->setIfExists('date_created', $data ?? [], null);
        $this->setIfExists('date_updated', $data ?? [], null);
        $this->setIfExists('constraints', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['fee_type'] === null) {
            $invalidProperties[] = "'fee_type' can't be null";
        }
        if ($this->container['include_initial_on_recurring_deposits'] === null) {
            $invalidProperties[] = "'include_initial_on_recurring_deposits' can't be null";
        }
        if ($this->container['is_vat_applicable'] === null) {
            $invalidProperties[] = "'is_vat_applicable' can't be null";
        }
        if ($this->container['ref'] === null) {
            $invalidProperties[] = "'ref' can't be null";
        }
        if ($this->container['tiers'] === null) {
            $invalidProperties[] = "'tiers' can't be null";
        }
        if ($this->container['date_created'] === null) {
            $invalidProperties[] = "'date_created' can't be null";
        }
        if ($this->container['date_updated'] === null) {
            $invalidProperties[] = "'date_updated' can't be null";
        }
        if ($this->container['constraints'] === null) {
            $invalidProperties[] = "'constraints' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets fee_type
     *
     * @return \OpenAPI\Client\Model\FapiDbFeeFeeScheduleFeeType
     */
    public function getFeeType()
    {
        return $this->container['fee_type'];
    }

    /**
     * Sets fee_type
     *
     * @param \OpenAPI\Client\Model\FapiDbFeeFeeScheduleFeeType $fee_type fee_type
     *
     * @return self
     */
    public function setFeeType($fee_type)
    {
        if (is_null($fee_type)) {
            throw new \InvalidArgumentException('non-nullable fee_type cannot be null');
        }
        $this->container['fee_type'] = $fee_type;

        return $this;
    }

    /**
     * Gets fee_calculation_type
     *
     * @return \OpenAPI\Client\Model\FeeCalculationType|null
     */
    public function getFeeCalculationType()
    {
        return $this->container['fee_calculation_type'];
    }

    /**
     * Sets fee_calculation_type
     *
     * @param \OpenAPI\Client\Model\FeeCalculationType|null $fee_calculation_type fee_calculation_type
     *
     * @return self
     */
    public function setFeeCalculationType($fee_calculation_type)
    {
        if (is_null($fee_calculation_type)) {
            throw new \InvalidArgumentException('non-nullable fee_calculation_type cannot be null');
        }
        $this->container['fee_calculation_type'] = $fee_calculation_type;

        return $this;
    }

    /**
     * Gets fee_charge_frequency
     *
     * @return \OpenAPI\Client\Model\FeeChargeFrequencyType|null
     */
    public function getFeeChargeFrequency()
    {
        return $this->container['fee_charge_frequency'];
    }

    /**
     * Sets fee_charge_frequency
     *
     * @param \OpenAPI\Client\Model\FeeChargeFrequencyType|null $fee_charge_frequency fee_charge_frequency
     *
     * @return self
     */
    public function setFeeChargeFrequency($fee_charge_frequency)
    {
        if (is_null($fee_charge_frequency)) {
            throw new \InvalidArgumentException('non-nullable fee_charge_frequency cannot be null');
        }
        $this->container['fee_charge_frequency'] = $fee_charge_frequency;

        return $this;
    }

    /**
     * Gets include_initial_on_recurring_deposits
     *
     * @return bool
     */
    public function getIncludeInitialOnRecurringDeposits()
    {
        return $this->container['include_initial_on_recurring_deposits'];
    }

    /**
     * Sets include_initial_on_recurring_deposits
     *
     * @param bool $include_initial_on_recurring_deposits include_initial_on_recurring_deposits
     *
     * @return self
     */
    public function setIncludeInitialOnRecurringDeposits($include_initial_on_recurring_deposits)
    {
        if (is_null($include_initial_on_recurring_deposits)) {
            throw new \InvalidArgumentException('non-nullable include_initial_on_recurring_deposits cannot be null');
        }
        $this->container['include_initial_on_recurring_deposits'] = $include_initial_on_recurring_deposits;

        return $this;
    }

    /**
     * Gets is_vat_applicable
     *
     * @return bool
     */
    public function getIsVatApplicable()
    {
        return $this->container['is_vat_applicable'];
    }

    /**
     * Sets is_vat_applicable
     *
     * @param bool $is_vat_applicable is_vat_applicable
     *
     * @return self
     */
    public function setIsVatApplicable($is_vat_applicable)
    {
        if (is_null($is_vat_applicable)) {
            throw new \InvalidArgumentException('non-nullable is_vat_applicable cannot be null');
        }
        $this->container['is_vat_applicable'] = $is_vat_applicable;

        return $this;
    }

    /**
     * Gets ref
     *
     * @return int
     */
    public function getRef()
    {
        return $this->container['ref'];
    }

    /**
     * Sets ref
     *
     * @param int $ref ref
     *
     * @return self
     */
    public function setRef($ref)
    {
        if (is_null($ref)) {
            throw new \InvalidArgumentException('non-nullable ref cannot be null');
        }
        $this->container['ref'] = $ref;

        return $this;
    }

    /**
     * Gets tiers
     *
     * @return \OpenAPI\Client\Model\FeeScheduleTierReturnSchema[]
     */
    public function getTiers()
    {
        return $this->container['tiers'];
    }

    /**
     * Sets tiers
     *
     * @param \OpenAPI\Client\Model\FeeScheduleTierReturnSchema[] $tiers tiers
     *
     * @return self
     */
    public function setTiers($tiers)
    {
        if (is_null($tiers)) {
            throw new \InvalidArgumentException('non-nullable tiers cannot be null');
        }
        $this->container['tiers'] = $tiers;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return \DateTime
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param \DateTime $date_created date_created
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            throw new \InvalidArgumentException('non-nullable date_created cannot be null');
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets date_updated
     *
     * @return \DateTime
     */
    public function getDateUpdated()
    {
        return $this->container['date_updated'];
    }

    /**
     * Sets date_updated
     *
     * @param \DateTime $date_updated date_updated
     *
     * @return self
     */
    public function setDateUpdated($date_updated)
    {
        if (is_null($date_updated)) {
            throw new \InvalidArgumentException('non-nullable date_updated cannot be null');
        }
        $this->container['date_updated'] = $date_updated;

        return $this;
    }

    /**
     * Gets constraints
     *
     * @return \OpenAPI\Client\Model\FeeScheduleConstraintReturnSchema
     */
    public function getConstraints()
    {
        return $this->container['constraints'];
    }

    /**
     * Sets constraints
     *
     * @param \OpenAPI\Client\Model\FeeScheduleConstraintReturnSchema $constraints constraints
     *
     * @return self
     */
    public function setConstraints($constraints)
    {
        if (is_null($constraints)) {
            throw new \InvalidArgumentException('non-nullable constraints cannot be null');
        }
        $this->container['constraints'] = $constraints;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


