<?php
/**
 * InvStrategyAuditReturnSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InvStrategyAuditReturnSchema Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InvStrategyAuditReturnSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InvStrategyAuditReturnSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'update_description' => 'string',
        'id' => 'int',
        'editor_id' => 'int',
        'edit_datetime' => '\DateTime',
        'approver_id' => 'int',
        'approval_datetime' => '\DateTime',
        'update_datetime' => '\DateTime',
        'status' => '\OpenAPI\Client\Model\FapiDbInvstrategyInvStrategyAuditStatus',
        'rationale_doc_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'update_description' => null,
        'id' => null,
        'editor_id' => null,
        'edit_datetime' => 'date-time',
        'approver_id' => null,
        'approval_datetime' => 'date-time',
        'update_datetime' => 'date-time',
        'status' => null,
        'rationale_doc_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'update_description' => false,
        'id' => false,
        'editor_id' => false,
        'edit_datetime' => false,
        'approver_id' => false,
        'approval_datetime' => false,
        'update_datetime' => false,
        'status' => false,
        'rationale_doc_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'update_description' => 'update_description',
        'id' => 'id',
        'editor_id' => 'editor_id',
        'edit_datetime' => 'edit_datetime',
        'approver_id' => 'approver_id',
        'approval_datetime' => 'approval_datetime',
        'update_datetime' => 'update_datetime',
        'status' => 'status',
        'rationale_doc_id' => 'rationale_doc_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'update_description' => 'setUpdateDescription',
        'id' => 'setId',
        'editor_id' => 'setEditorId',
        'edit_datetime' => 'setEditDatetime',
        'approver_id' => 'setApproverId',
        'approval_datetime' => 'setApprovalDatetime',
        'update_datetime' => 'setUpdateDatetime',
        'status' => 'setStatus',
        'rationale_doc_id' => 'setRationaleDocId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'update_description' => 'getUpdateDescription',
        'id' => 'getId',
        'editor_id' => 'getEditorId',
        'edit_datetime' => 'getEditDatetime',
        'approver_id' => 'getApproverId',
        'approval_datetime' => 'getApprovalDatetime',
        'update_datetime' => 'getUpdateDatetime',
        'status' => 'getStatus',
        'rationale_doc_id' => 'getRationaleDocId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('update_description', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('editor_id', $data ?? [], null);
        $this->setIfExists('edit_datetime', $data ?? [], null);
        $this->setIfExists('approver_id', $data ?? [], null);
        $this->setIfExists('approval_datetime', $data ?? [], null);
        $this->setIfExists('update_datetime', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('rationale_doc_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['update_datetime'] === null) {
            $invalidProperties[] = "'update_datetime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets update_description
     *
     * @return string|null
     */
    public function getUpdateDescription()
    {
        return $this->container['update_description'];
    }

    /**
     * Sets update_description
     *
     * @param string|null $update_description update_description
     *
     * @return self
     */
    public function setUpdateDescription($update_description)
    {
        if (is_null($update_description)) {
            throw new \InvalidArgumentException('non-nullable update_description cannot be null');
        }
        $this->container['update_description'] = $update_description;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets editor_id
     *
     * @return int|null
     */
    public function getEditorId()
    {
        return $this->container['editor_id'];
    }

    /**
     * Sets editor_id
     *
     * @param int|null $editor_id editor_id
     *
     * @return self
     */
    public function setEditorId($editor_id)
    {
        if (is_null($editor_id)) {
            throw new \InvalidArgumentException('non-nullable editor_id cannot be null');
        }
        $this->container['editor_id'] = $editor_id;

        return $this;
    }

    /**
     * Gets edit_datetime
     *
     * @return \DateTime|null
     */
    public function getEditDatetime()
    {
        return $this->container['edit_datetime'];
    }

    /**
     * Sets edit_datetime
     *
     * @param \DateTime|null $edit_datetime edit_datetime
     *
     * @return self
     */
    public function setEditDatetime($edit_datetime)
    {
        if (is_null($edit_datetime)) {
            throw new \InvalidArgumentException('non-nullable edit_datetime cannot be null');
        }
        $this->container['edit_datetime'] = $edit_datetime;

        return $this;
    }

    /**
     * Gets approver_id
     *
     * @return int|null
     */
    public function getApproverId()
    {
        return $this->container['approver_id'];
    }

    /**
     * Sets approver_id
     *
     * @param int|null $approver_id approver_id
     *
     * @return self
     */
    public function setApproverId($approver_id)
    {
        if (is_null($approver_id)) {
            throw new \InvalidArgumentException('non-nullable approver_id cannot be null');
        }
        $this->container['approver_id'] = $approver_id;

        return $this;
    }

    /**
     * Gets approval_datetime
     *
     * @return \DateTime|null
     */
    public function getApprovalDatetime()
    {
        return $this->container['approval_datetime'];
    }

    /**
     * Sets approval_datetime
     *
     * @param \DateTime|null $approval_datetime approval_datetime
     *
     * @return self
     */
    public function setApprovalDatetime($approval_datetime)
    {
        if (is_null($approval_datetime)) {
            throw new \InvalidArgumentException('non-nullable approval_datetime cannot be null');
        }
        $this->container['approval_datetime'] = $approval_datetime;

        return $this;
    }

    /**
     * Gets update_datetime
     *
     * @return \DateTime
     */
    public function getUpdateDatetime()
    {
        return $this->container['update_datetime'];
    }

    /**
     * Sets update_datetime
     *
     * @param \DateTime $update_datetime update_datetime
     *
     * @return self
     */
    public function setUpdateDatetime($update_datetime)
    {
        if (is_null($update_datetime)) {
            throw new \InvalidArgumentException('non-nullable update_datetime cannot be null');
        }
        $this->container['update_datetime'] = $update_datetime;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\FapiDbInvstrategyInvStrategyAuditStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\FapiDbInvstrategyInvStrategyAuditStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets rationale_doc_id
     *
     * @return int|null
     */
    public function getRationaleDocId()
    {
        return $this->container['rationale_doc_id'];
    }

    /**
     * Sets rationale_doc_id
     *
     * @param int|null $rationale_doc_id rationale_doc_id
     *
     * @return self
     */
    public function setRationaleDocId($rationale_doc_id)
    {
        if (is_null($rationale_doc_id)) {
            throw new \InvalidArgumentException('non-nullable rationale_doc_id cannot be null');
        }
        $this->container['rationale_doc_id'] = $rationale_doc_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


