<?php
/**
 * PublicAdviserFirmReturnSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PublicAdviserFirmReturnSchema Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PublicAdviserFirmReturnSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PublicAdviserFirmReturnSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ref' => 'string',
        'firm_name' => 'string',
        'firm_type' => 'string',
        'phone_number' => 'string',
        'support_email' => 'string',
        'companies_house_registration_number' => 'string',
        'fca_registration_number' => 'string',
        'style' => 'string',
        'addresses' => '\OpenAPI\Client\Model\AdviserFirmAddressReturnSchema[]',
        'subdomain' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ref' => null,
        'firm_name' => null,
        'firm_type' => null,
        'phone_number' => null,
        'support_email' => 'email',
        'companies_house_registration_number' => null,
        'fca_registration_number' => null,
        'style' => null,
        'addresses' => null,
        'subdomain' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'ref' => false,
        'firm_name' => false,
        'firm_type' => false,
        'phone_number' => false,
        'support_email' => false,
        'companies_house_registration_number' => false,
        'fca_registration_number' => false,
        'style' => false,
        'addresses' => false,
        'subdomain' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ref' => 'ref',
        'firm_name' => 'firm_name',
        'firm_type' => 'firm_type',
        'phone_number' => 'phone_number',
        'support_email' => 'support_email',
        'companies_house_registration_number' => 'companies_house_registration_number',
        'fca_registration_number' => 'fca_registration_number',
        'style' => 'style',
        'addresses' => 'addresses',
        'subdomain' => 'subdomain'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ref' => 'setRef',
        'firm_name' => 'setFirmName',
        'firm_type' => 'setFirmType',
        'phone_number' => 'setPhoneNumber',
        'support_email' => 'setSupportEmail',
        'companies_house_registration_number' => 'setCompaniesHouseRegistrationNumber',
        'fca_registration_number' => 'setFcaRegistrationNumber',
        'style' => 'setStyle',
        'addresses' => 'setAddresses',
        'subdomain' => 'setSubdomain'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ref' => 'getRef',
        'firm_name' => 'getFirmName',
        'firm_type' => 'getFirmType',
        'phone_number' => 'getPhoneNumber',
        'support_email' => 'getSupportEmail',
        'companies_house_registration_number' => 'getCompaniesHouseRegistrationNumber',
        'fca_registration_number' => 'getFcaRegistrationNumber',
        'style' => 'getStyle',
        'addresses' => 'getAddresses',
        'subdomain' => 'getSubdomain'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('ref', $data ?? [], null);
        $this->setIfExists('firm_name', $data ?? [], null);
        $this->setIfExists('firm_type', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('support_email', $data ?? [], null);
        $this->setIfExists('companies_house_registration_number', $data ?? [], null);
        $this->setIfExists('fca_registration_number', $data ?? [], null);
        $this->setIfExists('style', $data ?? [], null);
        $this->setIfExists('addresses', $data ?? [], null);
        $this->setIfExists('subdomain', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ref'] === null) {
            $invalidProperties[] = "'ref' can't be null";
        }
        if ((mb_strlen($this->container['ref']) > 6)) {
            $invalidProperties[] = "invalid value for 'ref', the character length must be smaller than or equal to 6.";
        }

        if ($this->container['firm_name'] === null) {
            $invalidProperties[] = "'firm_name' can't be null";
        }
        if ($this->container['firm_type'] === null) {
            $invalidProperties[] = "'firm_type' can't be null";
        }
        if ($this->container['phone_number'] === null) {
            $invalidProperties[] = "'phone_number' can't be null";
        }
        if (!preg_match("/^\\s*(?:\\+?(\\d{1,6}))?[-.\\s(]*(\\d{1,6})[-.\\s)]*(\\d{1,6})([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?(?: *(\\d+))?\\s*$/", $this->container['phone_number'])) {
            $invalidProperties[] = "invalid value for 'phone_number', must be conform to the pattern /^\\s*(?:\\+?(\\d{1,6}))?[-.\\s(]*(\\d{1,6})[-.\\s)]*(\\d{1,6})([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?(?: *(\\d+))?\\s*$/.";
        }

        if ($this->container['support_email'] === null) {
            $invalidProperties[] = "'support_email' can't be null";
        }
        if (!is_null($this->container['fca_registration_number']) && !preg_match("/^1?[0-9]{6}$/", $this->container['fca_registration_number'])) {
            $invalidProperties[] = "invalid value for 'fca_registration_number', must be conform to the pattern /^1?[0-9]{6}$/.";
        }

        if ($this->container['style'] === null) {
            $invalidProperties[] = "'style' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ref
     *
     * @return string
     */
    public function getRef()
    {
        return $this->container['ref'];
    }

    /**
     * Sets ref
     *
     * @param string $ref ref
     *
     * @return self
     */
    public function setRef($ref)
    {
        if (is_null($ref)) {
            throw new \InvalidArgumentException('non-nullable ref cannot be null');
        }
        if ((mb_strlen($ref) > 6)) {
            throw new \InvalidArgumentException('invalid length for $ref when calling PublicAdviserFirmReturnSchema., must be smaller than or equal to 6.');
        }

        $this->container['ref'] = $ref;

        return $this;
    }

    /**
     * Gets firm_name
     *
     * @return string
     */
    public function getFirmName()
    {
        return $this->container['firm_name'];
    }

    /**
     * Sets firm_name
     *
     * @param string $firm_name firm_name
     *
     * @return self
     */
    public function setFirmName($firm_name)
    {
        if (is_null($firm_name)) {
            throw new \InvalidArgumentException('non-nullable firm_name cannot be null');
        }
        $this->container['firm_name'] = $firm_name;

        return $this;
    }

    /**
     * Gets firm_type
     *
     * @return string
     */
    public function getFirmType()
    {
        return $this->container['firm_type'];
    }

    /**
     * Sets firm_type
     *
     * @param string $firm_type firm_type
     *
     * @return self
     */
    public function setFirmType($firm_type)
    {
        if (is_null($firm_type)) {
            throw new \InvalidArgumentException('non-nullable firm_type cannot be null');
        }
        $this->container['firm_type'] = $firm_type;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string $phone_number Must be a string of numbers and special characters (\"()\", \"-\", \"+\", \" \")
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            throw new \InvalidArgumentException('non-nullable phone_number cannot be null');
        }

        if ((!preg_match("/^\\s*(?:\\+?(\\d{1,6}))?[-.\\s(]*(\\d{1,6})[-.\\s)]*(\\d{1,6})([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?(?: *(\\d+))?\\s*$/", ObjectSerializer::toString($phone_number)))) {
            throw new \InvalidArgumentException("invalid value for \$phone_number when calling PublicAdviserFirmReturnSchema., must conform to the pattern /^\\s*(?:\\+?(\\d{1,6}))?[-.\\s(]*(\\d{1,6})[-.\\s)]*(\\d{1,6})([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?([-.\\s]*(\\d{1,6})[-.\\s]*)?(?: *(\\d+))?\\s*$/.");
        }

        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets support_email
     *
     * @return string
     */
    public function getSupportEmail()
    {
        return $this->container['support_email'];
    }

    /**
     * Sets support_email
     *
     * @param string $support_email support_email
     *
     * @return self
     */
    public function setSupportEmail($support_email)
    {
        if (is_null($support_email)) {
            throw new \InvalidArgumentException('non-nullable support_email cannot be null');
        }
        $this->container['support_email'] = $support_email;

        return $this;
    }

    /**
     * Gets companies_house_registration_number
     *
     * @return string|null
     */
    public function getCompaniesHouseRegistrationNumber()
    {
        return $this->container['companies_house_registration_number'];
    }

    /**
     * Sets companies_house_registration_number
     *
     * @param string|null $companies_house_registration_number companies_house_registration_number
     *
     * @return self
     */
    public function setCompaniesHouseRegistrationNumber($companies_house_registration_number)
    {
        if (is_null($companies_house_registration_number)) {
            throw new \InvalidArgumentException('non-nullable companies_house_registration_number cannot be null');
        }
        $this->container['companies_house_registration_number'] = $companies_house_registration_number;

        return $this;
    }

    /**
     * Gets fca_registration_number
     *
     * @return string|null
     */
    public function getFcaRegistrationNumber()
    {
        return $this->container['fca_registration_number'];
    }

    /**
     * Sets fca_registration_number
     *
     * @param string|null $fca_registration_number Must be a valid FCA registration number
     *
     * @return self
     */
    public function setFcaRegistrationNumber($fca_registration_number)
    {
        if (is_null($fca_registration_number)) {
            throw new \InvalidArgumentException('non-nullable fca_registration_number cannot be null');
        }

        if ((!preg_match("/^1?[0-9]{6}$/", ObjectSerializer::toString($fca_registration_number)))) {
            throw new \InvalidArgumentException("invalid value for \$fca_registration_number when calling PublicAdviserFirmReturnSchema., must conform to the pattern /^1?[0-9]{6}$/.");
        }

        $this->container['fca_registration_number'] = $fca_registration_number;

        return $this;
    }

    /**
     * Gets style
     *
     * @return string
     */
    public function getStyle()
    {
        return $this->container['style'];
    }

    /**
     * Sets style
     *
     * @param string $style style
     *
     * @return self
     */
    public function setStyle($style)
    {
        if (is_null($style)) {
            throw new \InvalidArgumentException('non-nullable style cannot be null');
        }
        $this->container['style'] = $style;

        return $this;
    }

    /**
     * Gets addresses
     *
     * @return \OpenAPI\Client\Model\AdviserFirmAddressReturnSchema[]|null
     */
    public function getAddresses()
    {
        return $this->container['addresses'];
    }

    /**
     * Sets addresses
     *
     * @param \OpenAPI\Client\Model\AdviserFirmAddressReturnSchema[]|null $addresses addresses
     *
     * @return self
     */
    public function setAddresses($addresses)
    {
        if (is_null($addresses)) {
            throw new \InvalidArgumentException('non-nullable addresses cannot be null');
        }
        $this->container['addresses'] = $addresses;

        return $this;
    }

    /**
     * Gets subdomain
     *
     * @return string|null
     */
    public function getSubdomain()
    {
        return $this->container['subdomain'];
    }

    /**
     * Sets subdomain
     *
     * @param string|null $subdomain subdomain
     *
     * @return self
     */
    public function setSubdomain($subdomain)
    {
        if (is_null($subdomain)) {
            throw new \InvalidArgumentException('non-nullable subdomain cannot be null');
        }
        $this->container['subdomain'] = $subdomain;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


