<?php
/**
 * UserRelationship
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UserRelationship Class Doc Comment
 *
 * @category Class
 * @description [{\&quot;name\&quot;: \&quot;Lead\&quot;, \&quot;value\&quot;: \&quot;LEAD\&quot;}, {\&quot;name\&quot;: \&quot;Spouse\&quot;, \&quot;value\&quot;: \&quot;SPOUSE\&quot;}, {\&quot;name\&quot;: \&quot;Child At Same Address\&quot;, \&quot;value\&quot;: \&quot;CHILD_AT_SAME_ADDRESS\&quot;}, {\&quot;name\&quot;: \&quot;Other\&quot;, \&quot;value\&quot;: \&quot;OTHER\&quot;}]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserRelationship
{
    /**
     * Possible values of this enum
     */
    public const LEAD = 'LEAD';

    public const SPOUSE = 'SPOUSE';

    public const CHILD_AT_SAME_ADDRESS = 'CHILD_AT_SAME_ADDRESS';

    public const OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LEAD,
            self::SPOUSE,
            self::CHILD_AT_SAME_ADDRESS,
            self::OTHER
        ];
    }
}


