<?php
/**
 * ClientTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ClientTypeTest Class Doc Comment
 *
 * @category    Class
 * @description [{\&quot;name\&quot;: \&quot;Individual\&quot;, \&quot;value\&quot;: \&quot;INDV\&quot;}, {\&quot;name\&quot;: \&quot;Individual Junior\&quot;, \&quot;value\&quot;: \&quot;INDV_JUNIOR\&quot;}, {\&quot;name\&quot;: \&quot;Corporate\&quot;, \&quot;value\&quot;: \&quot;CORPORATE\&quot;}, {\&quot;name\&quot;: \&quot;Trust\&quot;, \&quot;value\&quot;: \&quot;TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Charity\&quot;, \&quot;value\&quot;: \&quot;CHARITY\&quot;}, {\&quot;name\&quot;: \&quot;Partnership\&quot;, \&quot;value\&quot;: \&quot;PARTNERSHIP\&quot;}, {\&quot;name\&quot;: \&quot;Bare Trust\&quot;, \&quot;value\&quot;: \&quot;BARE_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Discretionary Trust\&quot;, \&quot;value\&quot;: \&quot;DISCRETIONARY_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Gift Trust\&quot;, \&quot;value\&quot;: \&quot;GIFT_TRUST\&quot;}, {\&quot;name\&quot;: \&quot;Ssas\&quot;, \&quot;value\&quot;: \&quot;SSAS\&quot;}]
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ClientTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ClientType"
     */
    public function testClientType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
