<?php
/**
 * DropNotificationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DropNotificationTest Class Doc Comment
 *
 * @category    Class
 * @description [{\&quot;name\&quot;: \&quot;Client\&quot;, \&quot;value\&quot;: \&quot;CLIENT\&quot;}, {\&quot;name\&quot;: \&quot;Adviser\&quot;, \&quot;value\&quot;: \&quot;ADVISER\&quot;}, {\&quot;name\&quot;: \&quot;Investment Management Firm\&quot;, \&quot;value\&quot;: \&quot;INVMGR\&quot;}, {\&quot;name\&quot;: \&quot;Client Adviser\&quot;, \&quot;value\&quot;: \&quot;CLIENT_ADVISER\&quot;}, {\&quot;name\&quot;: \&quot;Client Investment Management Firm\&quot;, \&quot;value\&quot;: \&quot;CLIENT_INVMGR\&quot;}, {\&quot;name\&quot;: \&quot;Adviser Investment Management Firm\&quot;, \&quot;value\&quot;: \&quot;ADVISER_INVMGR\&quot;}, {\&quot;name\&quot;: \&quot;All\&quot;, \&quot;value\&quot;: \&quot;ALL\&quot;}]
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DropNotificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DropNotification"
     */
    public function testDropNotification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
