<?php
/**
 * HTTPStatusTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HTTPStatusTest Class Doc Comment
 *
 * @category    Class
 * @description HTTP status codes and reason phrases  Status codes from the following RFCs are all observed:      * RFC 7231: Hypertext Transfer Protocol (HTTP/1.1), obsoletes 2616     * RFC 6585: Additional HTTP Status Codes     * RFC 3229: Delta encoding in HTTP     * RFC 4918: HTTP Extensions for WebDAV, obsoletes 2518     * RFC 5842: Binding Extensions to WebDAV     * RFC 7238: Permanent Redirect     * RFC 2295: Transparent Content Negotiation in HTTP     * RFC 2774: An HTTP Extension Framework     * RFC 7540: Hypertext Transfer Protocol Version 2 (HTTP/2)
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HTTPStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HTTPStatus"
     */
    public function testHTTPStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
