<?php
/**
 * ReportTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReportTypeTest Class Doc Comment
 *
 * @category    Class
 * @description [{\&quot;name\&quot;: \&quot;Adviser\&quot;, \&quot;value\&quot;: \&quot;ADVISER\&quot;}, {\&quot;name\&quot;: \&quot;Invmgr\&quot;, \&quot;value\&quot;: \&quot;INVMGR\&quot;}, {\&quot;name\&quot;: \&quot;Client\&quot;, \&quot;value\&quot;: \&quot;CLIENT\&quot;}, {\&quot;name\&quot;: \&quot;Wrapsupplier\&quot;, \&quot;value\&quot;: \&quot;WRAPSUPPLIER\&quot;}, {\&quot;name\&quot;: \&quot;Platform\&quot;, \&quot;value\&quot;: \&quot;PLATFORM\&quot;}]
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReportTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReportType"
     */
    public function testReportType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
