<?php
/**
 * PensionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PensionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PensionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for pensionEventCancel
     *
     * Pension Event Cancel.
     *
     */
    public function testPensionEventCancel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventGroupRead
     *
     * Pension Event Group Read.
     *
     */
    public function testPensionEventGroupRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventRead
     *
     * Pension Event Read.
     *
     */
    public function testPensionEventRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventScheduleCancel
     *
     * Pension Event Schedule Cancel.
     *
     */
    public function testPensionEventScheduleCancel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventScheduleCreate
     *
     * Pension Event Schedule Create.
     *
     */
    public function testPensionEventScheduleCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventScheduleGroupCreate
     *
     * Pension Event Schedule Group Create.
     *
     */
    public function testPensionEventScheduleGroupCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventScheduleRead
     *
     * Pension Event Schedule Read.
     *
     */
    public function testPensionEventScheduleRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventScheduleUpdate
     *
     * Pension Event Schedule Update.
     *
     */
    public function testPensionEventScheduleUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventSchedulesGet
     *
     * Pension Event Schedules Get.
     *
     */
    public function testPensionEventSchedulesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionEventsGet
     *
     * Pension Events Get.
     *
     */
    public function testPensionEventsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionScheduleGroupCancel
     *
     * Pension Schedule Group Cancel.
     *
     */
    public function testPensionScheduleGroupCancel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionScheduleGroupRead
     *
     * Pension Schedule Group Read.
     *
     */
    public function testPensionScheduleGroupRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pensionScheduleGroupReadEvents
     *
     * Pension Schedule Group Read Events.
     *
     */
    public function testPensionScheduleGroupReadEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readPensionEventScheduleGroupsForAccount
     *
     * Read Pension Event Schedule Groups For Account.
     *
     */
    public function testReadPensionEventScheduleGroupsForAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readPensionEventSchedulesForAccount
     *
     * Read Pension Event Schedules For Account.
     *
     */
    public function testReadPensionEventSchedulesForAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readPensionEventsForAccount
     *
     * Read Pension Events For Account.
     *
     */
    public function testReadPensionEventsForAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
