<?php
/**
 * ReportAccessApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fundment API
 *
 * <div><a href=\"/staging/\"><h1>Getting started</h1></a> </div>
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportAccessApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportAccessApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for reportCreate
     *
     * Report Create.
     *
     */
    public function testReportCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportDelete
     *
     * Report Delete.
     *
     */
    public function testReportDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupCreate
     *
     * Report Group Create.
     *
     */
    public function testReportGroupCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupDelete
     *
     * Report Group Delete.
     *
     */
    public function testReportGroupDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupMemberCreate
     *
     * Report Group Member Create.
     *
     */
    public function testReportGroupMemberCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupMemberDelete
     *
     * Report Group Member Delete.
     *
     */
    public function testReportGroupMemberDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupMemberUpdate
     *
     * Report Group Member Update.
     *
     */
    public function testReportGroupMemberUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupMembersRead
     *
     * Report Group Members Read.
     *
     */
    public function testReportGroupMembersRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupPermissionCreate
     *
     * Report Group Permission Create.
     *
     */
    public function testReportGroupPermissionCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupPermissionDelete
     *
     * Report Group Permission Delete.
     *
     */
    public function testReportGroupPermissionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupPermissionForLoginRead
     *
     * Report Group Permission For Login Read.
     *
     */
    public function testReportGroupPermissionForLoginRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupPermissionUpdate
     *
     * Report Group Permission Update.
     *
     */
    public function testReportGroupPermissionUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupPermissionsRead
     *
     * Report Group Permissions Read.
     *
     */
    public function testReportGroupPermissionsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupUpdate
     *
     * Report Group Update.
     *
     */
    public function testReportGroupUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportGroupsRead
     *
     * Report Groups Read.
     *
     */
    public function testReportGroupsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUpdate
     *
     * Report Update.
     *
     */
    public function testReportUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupCreate
     *
     * Report User Group Create.
     *
     */
    public function testReportUserGroupCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupDelete
     *
     * Report User Group Delete.
     *
     */
    public function testReportUserGroupDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupMemberCreate
     *
     * Report User Group Member Create.
     *
     */
    public function testReportUserGroupMemberCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupMemberDelete
     *
     * Report User Group Member Delete.
     *
     */
    public function testReportUserGroupMemberDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupMemberRead
     *
     * Report User Group Member Read.
     *
     */
    public function testReportUserGroupMemberRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupMemberUpdate
     *
     * Report User Group Member Update.
     *
     */
    public function testReportUserGroupMemberUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupRead
     *
     * Report User Group Read.
     *
     */
    public function testReportUserGroupRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportUserGroupUpdate
     *
     * Report User Group Update.
     *
     */
    public function testReportUserGroupUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportsRead
     *
     * Reports Read.
     *
     */
    public function testReportsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
